server:
  port: 8888

#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false

spring:
  application:
    name: config-client
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liuliuname/config-repo-demo
          username: liuliuname
          password: liuliu230229
